// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY6_tfxdrP42bWB6qZxvfUxCHbqiYoCRA',
    appId: '1:811790952024:web:badd9a74d8750a56d50c2d',
    messagingSenderId: '811790952024',
    projectId: 'tuneflow-9a028',
    authDomain: 'tuneflow-9a028.firebaseapp.com',
    storageBucket: 'tuneflow-9a028.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm2lCQksNmFOX8XJ9Ba0ch-_96i0O9dBc',
    appId: '1:811790952024:android:a40aa4c5230efaa1d50c2d',
    messagingSenderId: '811790952024',
    projectId: 'tuneflow-9a028',
    storageBucket: 'tuneflow-9a028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYeCxrG2tbzORt9swgKZWixGDpTcew5Jk',
    appId: '1:811790952024:ios:87b82099c8c31d29d50c2d',
    messagingSenderId: '811790952024',
    projectId: 'tuneflow-9a028',
    storageBucket: 'tuneflow-9a028.appspot.com',
    iosBundleId: 'com.example.tuneflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYeCxrG2tbzORt9swgKZWixGDpTcew5Jk',
    appId: '1:811790952024:ios:87b82099c8c31d29d50c2d',
    messagingSenderId: '811790952024',
    projectId: 'tuneflow-9a028',
    storageBucket: 'tuneflow-9a028.appspot.com',
    iosBundleId: 'com.example.tuneflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY6_tfxdrP42bWB6qZxvfUxCHbqiYoCRA',
    appId: '1:811790952024:web:34d34f1dad1ec31bd50c2d',
    messagingSenderId: '811790952024',
    projectId: 'tuneflow-9a028',
    authDomain: 'tuneflow-9a028.firebaseapp.com',
    storageBucket: 'tuneflow-9a028.appspot.com',
  );

}